# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
	'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
	'RCTText',
	'RCTImage',
	'RCTNetwork',
	'RCTActionSheet',
	'RCTLinkingIOS',
	'ART',
	'RCTAnimation',
    'RCTWebSocket', # needed for debugging
    # 'jschelpers',
    'cxxreact',
    'CxxBridge',
  ]
  # Pods for RNDemo
  pod 'IQKeyboardManager' #iOS8 and later
  pod "yoga", :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end
