# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNDemo
  pod 'IQKeyboardManager' #iOS8 and later

end
